[tool.poetry]
name = "OWASP Nest"
version = "0.1.0"
description = "Streamlines OWASP entities management"
authors = ["Arkadii Yakovets <arkadii.yakovets@owasp.org>"]
readme = "README.md"

packages = [{ include = "apps" }]

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1"
django-configurations = "^2.5.1"
lxml = "^5.3.0"
psycopg2 = "^2.9.9"
pygithub = "^2.3.0"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
ruff = "^0.5.7"
isort = "^5.13.2"

[tool.isort]
known_third_party = ["django"]
known_first_party = ["apps"]
multi_line_output = 3
profile = "black"

[tool.ruff]
line-length = 99
target-version = "py312"

[tool.ruff.lint]
ignore = [
    "ANN",
    "ARG002",
    "C901",
    "COM812",
    "DJ012",
    "ERA001",
    "FIX002",
    "PD",
    "PLC0414",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "RUF012",
    "TD003",
]
select = ["ALL"]

[tool.ruff.per-file-ignores]
"**/__init__.py" = ["D104", "F401"]
"**/admin.py" = ["D100", "D101", "D104"]
"**/apps.py" = ["D100", "D101", "D104"]
"**/management/commands/*.py" = ["D101", "D102", "T201"]
"**/migrations/*.py" = ["D100", "D101", "D104"]
"**/models.py" = ["D106"]
"**/models/*.py" = ["D106"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
