name: Issue manager

on:
  issue_comment:
    types:
      - created

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: owasp-actions/issue-manager@v0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
